"""Lint the deterministic structural subset of a publishable solution."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from util import cache_dir, parse_markdown, pid_normalize

AI_STATEMENTS = ("本文由 AI", "AI-generated", "Generated by", "Generated with")


def lint_text(text: str, enforce_default_style: bool = True) -> list[str]:
    body = parse_markdown(text)["body"]
    issues: list[str] = []
    in_fence = False
    fence_language = ""
    has_cpp = False
    has_idea = False
    has_code_heading = False
    for line_number, line in enumerate(body.splitlines(), 1):
        fence = re.match(r"^```([^\s`]*)", line)
        if fence:
            if in_fence:
                in_fence = False
                fence_language = ""
            else:
                in_fence = True
                fence_language = fence.group(1).lower()
                has_cpp = has_cpp or fence_language == "cpp"
            continue
        if not in_fence:
            if line.startswith("# "):
                issues.append(f"line {line_number}: 题解正文禁止 H1")
            if re.match(r"^#{3,6}\s", line):
                issues.append(f"line {line_number}: 题解标题最高为 H2")
            has_idea = has_idea or line.strip() == "## 解题思路"
            has_code_heading = has_code_heading or line.strip() == "## 参考代码"
        elif fence_language == "cpp" and enforce_default_style:
            if "//" in line or "/*" in line or "*/" in line:
                issues.append(f"line {line_number}: OI 代码原则上不写注释")
            if re.search(r"\bdp\b", line, re.IGNORECASE):
                issues.append(f"line {line_number}: DP 状态使用 f，不用 dp")
    if in_fence:
        issues.append("代码围栏未闭合")
    if not has_idea:
        issues.append("缺少 ## 解题思路")
    if not has_code_heading or not has_cpp:
        issues.append("缺少 ## 参考代码 或 cpp 代码块")
    for statement in AI_STATEMENTS:
        if statement.lower() in body.lower():
            issues.append(f"禁止泛化 AI 署名：{statement}")
    return issues


def resolve_source(value: str) -> Path:
    candidate = Path(value).expanduser()
    if candidate.suffix.lower() in {".md", ".mdx"} or candidate.exists() or "/" in value:
        return candidate.resolve()
    return cache_dir(pid_normalize(value)) / "solution.md"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", help="PID or Markdown/MDX path")
    parser.add_argument(
        "--structure-only",
        action="store_true",
        help="skip the bundled code profile when another explicit style checker is active",
    )
    args = parser.parse_args(argv[1:])
    path = resolve_source(args.source)
    if not path.exists():
        print(f"题解源文件不存在：{path}", file=sys.stderr)
        return 2
    issues = lint_text(
        path.read_text(encoding="utf-8"),
        enforce_default_style=not args.structure_only,
    )
    for issue in issues:
        print(issue, file=sys.stderr)
    if issues:
        return 1
    print(f"题解结构检查通过：{path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
